config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users

  resources :tasks do 
  	member do
  	put :change
  end
 end
  
  root 'pages#home'

  get 'about' => 'pages#about'

  get 'test' => 'pages#test'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	validates :content, presence: true, length: {minimum: 4, maximum: 300}

	belongs_to :user

	auto_html_for :content do
		html_escape
		image
		youtube(width: '100%', height: 250)
		link target: '_blank', rel: 'nofollow'
		simple_format
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	if current_user
  		redirect_to tasks_path
  	end
  end

  def about
  end

  def test
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :authenticate_user!
	before_action :set_task, only:[:edit, :update, :show, :destroy, :change]

	def index
		@to_do = current_user.tasks.where(state: 'to_do')
		@doing = current_user.tasks.where(state: 'doing')
		@done = current_user.tasks.where(state: 'done')
	end

	def new
		@task = Task.new
	end

	def edit
		
	end

	def create
		@task = current_user.tasks.new(tasks_params)
		if @task.save
			flash[:notice] = "task was successfully created"
			redirect_to task_path(@task)
		else
			render 'new'
		end
	end

	def update
		
		if @task.update(tasks_params)
			flash[:notice] = "Task was successfully updated"
			redirect_to task_path(@task)
		else
			render 'edit'
		end
	end

	def show
		
	end

	def destroy
		
		@task.destroy
		flash[:notice] = "Task was successfully deleted"
		redirect_to tasks_path
	end


	def change
		@task.update_attributes(state: params[:state])
		flash[:notice] = "Task status was successfully changed"
		redirect_to tasks_path
	end

	private

	def set_task
		@task = Task.find(params[:id])
	end 

	def tasks_params
		params.require(:task).permit(:content, :state)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to '<i class="fa fa-circle-o-notch"></i>Taskr'.html_safe, root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>

      <% else %>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Log In', new_user_session_path %></li>

      <% end %>
    </ul>

    
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <% flash.each do |name, msg| %>
    <%= msg %>
  <% end %>

  <div class= 'container'>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<p>about</p>

app/views/pages/home.html.erb
<div class= 'jumbotron'>

<h1><i class="fa fa-circle-o-notch"></i> Taskr</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
</div>

app/views/pages/test.html.erb
<div class = 'row'>
	<div class = 'col-md-4'>
	<h1>To Do</h1>
		<div class = 'panel panel-info'>
			<div class = 'panel-heading'>My To Do</div>
				<div class = 'panel-body'>This is my todo list</div>
					<div class = 'panel-footer'>This is the footer</div>
			
		</div>
	</div>

	<div class = 'col-md-4'>
	<h1>Doing</h1>
		<div class = 'panel panel-info'>
			<div class = 'panel-heading'>My Doing</div>
				<div class = 'panel-body'>This is my doing list</div>
					<div class = 'panel-footer'>This is the footer</div>
			</div>
	</div>
	<div class = 'col-md-4'>
		<h1>Done</h1>
			<div class = 'panel panel-info'>
			<div class = 'panel-heading'>My Done</div>
				<div class = 'panel-body'>This is my done list</div>
					<div class = 'panel-footer'>This is the footer</div>
			</div>
	</div>
</div>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
	<ul>
	<% @task.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

<%= simple_form_for @task, html: {class: 'form-signin'} do |f| %>

	<%= f.input :content, label: false, placeholder: 'Content', autofocus: true %>

	<%= f.button :submit, class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to 'Go back to all tasks', tasks_path %>

app/views/tasks/_task.html.erb
		<div class = 'panel panel-info'>
			<div class = 'panel-heading'><%= link_to edit_task_path(task) do %>

			Created: <%= time_ago_in_words(task.created_at) %> ago

			<% end %>

			<%= link_to 'x', task_path(task), method: :delete, data: {confirm: 'Are you sure?'}, class: 'pull-right' %>

			</div>
				<div class = 'panel-body'><%= raw(task.content_html) %></div>
					<div class = 'panel-footer'>
					  <div class= "btn-group btn-group-justified">
						<% if task.state == 'doing' %>
						<%= link_to '<i class = "fa fa-arrow-left"></i>'.html_safe, change_task_path(task, state: "to_do"), method: :put, class: 'btn btn-info btn-block' %>

						<%= link_to '<i class = "fa fa-arrow-right"></i>'.html_safe, change_task_path(task, state: "done"), method: :put, class: 'btn btn-info btn-block' %>

						<% elsif task.state == 'done' %>
						<%= link_to '<i class = "fa fa-arrow-left"></i>'.html_safe, change_task_path(task, state: "doing"), method: :put, class: 'btn btn-info btn-block' %>

						<% else %>
						<%= link_to '<i class = "fa fa-arrow-right"></i>'.html_safe, change_task_path(task, state: "doing"), method: :put, class: 'btn btn-info btn-block' %>
						<% end %>
					  </div>


		
					</div>
			
		</div>

app/views/tasks/edit.html.erb
<h2 class = 'text-center'>Edit task</h2>

<%= render 'form' %>

app/views/tasks/index.html.erb

<p><%= link_to 'New Task', new_task_path %></p>

<div class = 'row'>

	<div class = 'col-md-4'>
		<h1 class = 'text-center'>To Do</h1>
		<%= render @to_do %>
	</div>

	<div class = 'col-md-4'>
		<h1 class = 'text-center'>Doing</h1>
		<%= render @doing %>
	</div>

	<div class = 'col-md-4'>
		<h1 class = 'text-center'>Done</h1>
		<%= render @done %>
	</div>

</div>


app/views/tasks/new.html.erb
<h2 class = 'text-center'>new tasks</h2>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Showing Task</h1>

<strong>Content: </strong><%= @task.content %>
<strong>State: </strong><%= @task.state %>

<p>
<%= link_to 'All tasks', tasks_path %>|
<%= link_to 'Edit Task', edit_task_path(@task) %>

</p>